[common]
server_addr = office.wlst.vip
server_port = 10023

token = taoyangongchandang

# set admin address for control frpc's action by http api such as reload
admin_addr = 127.0.0.1
admin_port = 8117
admin_user = admin
admin_pwd = admin

[web80]
type = http
local_port = 80                                                                                                              
use_encryption = true
use_compression = true
custom_domains = kod.xyzjdays.xyz

[web443]
type = https
local_port = 443
use_encryption = true
use_compression = true
custom_domains = kod.xyzjdays.xyz

